### ISSUE TITLE
「60秒读懂世界」 获取数据失败！

### ISSUE THREAD

**Issue by Vckers** [LyLme/LyToday#1]
部署之后显示如题。

**Comment by LyLme** [comment]
检查服务器外网访问是否正常，注释commin文件隐藏报错信息排查

**Comment by Vckers** [comment]
(index):1 [冲突] Added synchronous DOM mutation listener to a 'DOMNodeInsertedIntoDocument' event. Consider using MutationObserver to make the page more responsive.
app.js:1 [冲突] 'setTimeout' handler took 83ms
common.js:1 [冲突] 'setTimeout' handler took 227ms

**Comment by LyLme** [comment]
不是这个吧

**Comment by Vckers** [comment]
<img src = 'https://img.vckers.com/imgs/2023/11/28/4e1685023877cb70.png' />
检查了服务器网络和网站日志都没有问题，用服务器shell命令也能获取到api数据，甚至换了服务器还是一样获取失败。

**Comment by LyLme** [comment]
域名发我看一下

**Comment by Vckers** [comment]
https://60s.vckers.com/

**Comment by LyLme** [comment]
删除重新部署一下，另外权限改755，应用到子目录，可能是没写入权限，导致新闻数据未缓存

**Comment by Vckers** [comment]
这个试过了，给777还是不行

**Comment by Vckers** [comment]
<img src = 'https://img.vckers.com/imgs/2023/11/29/d23b71fec7837506.png' />
早上起来看了下if判断这里，改了下错误返回文字用于区分，打开网页是报这个错。

**Comment by Vckers** [comment]
把你部署的备份一下，下载GitHub上的重新部署一下如果跟我一样说明项目之前更新了可能没有上传。

**Comment by LyLme** [comment]
没有更新，你的这个明显是文件获取不到，我看了一下你的api目录也没有也没有60s/index.php文件
- 请再次检查源码完整性
- 另外你再看一下缓存目录是否有新闻数据文件
- 你可以注释`common/common.php`文件第10行的禁用报错，改为如下
```php
//error_reporting(0);
```
然后将报错信息截图给我

**Comment by Vckers** [comment]
<img src = 'https://img.vckers.com/imgs/2023/11/29/b1071037ab779256.png' />

- api目录是有index.php的。
- 源码都是在
[Releases](https://github.com/LyLme/LyToday/releases)下载并解压的，完整性没有问题
- 源码解压下来缓存目录为空，访问一次后只有cache.json文件，没有以日期命名的.json；且所有文件是755权限。
- 禁用报错取消后访问，网站日志没有报错，前端也没有，其他我就不知道看哪里了。

**Comment by LyLme** [comment]
你用的接口不是我的吧，我看了一下你api目录下的60s接口返回接口停更了

**Comment by Vckers** [comment]
啊？我是直接解压的啊，没有改动任何东西。
就像我上面说的是不是大佬您之前更新了东西没有同步到GitHub，您看看是不是要更新一下呢？
如果是接口停更什么的，麻烦大佬告知一下最新接口呢？

**Comment by LyLme** [comment]
没有呀，你的这个接口和我的不一样呀

**Comment by Vckers** [comment]
我都是直接反代你的了，接口还不一样吗？

**Comment by LyLme** [comment]
2.0版本已修复
